### ISSUE TITLE
IE 兼容max-height

### ISSUE THREAD

**Issue by dragonir** [dragonir/BLOG_ISSUE#14]
## expression表达式

```css
.div{
  max-height: 100px;
  _height:expression(this.scrollHeight > 100 ? "100px" : "auto");
  overflow-y:auto;
}
```

这样就可以让div在ie和firefox中都实现max-height的效果

```css
.div{
  max-height: 100px;
  min-height:60px;
  _height:expression(this.scrollHeight > 100 ? "100px" : ( this.scrollHeight < 60 ? "60px" : "auto"));
  overflow-y:auto;
}
```

这样就可以让div在ie和firefox中都实现max-height和min-height的效果

## IE6支持max-height解决方法

IE6支持最大高度解决CSS代码：

```css
.yangshi{
  max-height:1000px;
  _height:expression((document.documentElement.clientHeight||document.body.clientHeight)<1000?"1000px":"");
  overflow:hidden;
}
```

说明：`max-height:1000px`; 这个是IE6以上级其它品牌浏览器支持最大范围高度。而 `_height:expression((document.documentElement.clientHeight||document.body.clientHeight)<1000?"1000px":"");overflow:hidden;` 则是让IE6支持 `max-height` 替代CSS代码，但效果和其它版本浏览器相同效果。这里的1000和1000px是你需要的数值，注意3个数值的相同。让 `IE6` 支持最大高度 `max-height` 的时候别忘记加上 `overflow:hidden`。

## IE6支持min-height解决方法

IE6支持最小高度解决CSS代码：

```css
.yangshi{
  min-height:1000px;
  _height:expression((document.documentElement.clientHeight||document.body.clientHeight)>1000?"1000px":"");
}
```

说明：`min-height:1000px`; 这个是`IE6`以上级其它品牌浏览器支持最小范围高度。而 `_height:expression((document.documentElement.clientHeight||document.body.clientHeight)>1000?"1000px":"")`;则是让`IE6`支持css `min-height` 替代CSS代码，但效果和其它版本浏览器相同效果。 这里的1000和1000px是你需要的数值，注意3个数值的相同。

## IE6支持max-height又支持min-height方法

让所有浏览器包括IE6即支持最大高度又支持最小高度：

```css
.yangshi{
  Max-Height:620px;
  Min-Height:40px;
  _height:expression(this.scrollHeight > 620 ? "620px" : (this.scrollHeight < 40 ? "40px" : "auto"));
  }
```

IE6支持 `Max-Height` 和支持 `Min-Height` CSS代码 `_height:expression(this.scrollHeight > 620 ? "620px" : (this.scrollHeight < 40 ? "40px" : "auto"))`;说明：以上代码作用是让对象的最小高度为40px，最大高度为620px的CSS样式属性
