### ISSUE TITLE
IE7 兼容 inline-block

### ISSUE THREAD

**Issue by dragonir** [dragonir/BLOG_ISSUE#15]
## 推荐:IE6、7

```css
 div {
    display:inline-block;
    *zoom:1;
    *display: inline;
 }
```

## 三者缺一不可

```css
div {
  display:inline-block;
  _zoom:1;
  _display:inline;
}
```
