### ISSUE TITLE
css去掉浏览器打印样式中的页眉和页脚

### ISSUE THREAD

**Issue by dragonir** [dragonir/BLOG_ISSUE#26]
css默认去掉浏览器打印样式中的页眉和页脚

```css
@page { margin: 0; }
```
