### ISSUE TITLE
css3动画控制的暂停与运行

### ISSUE THREAD

**Issue by dragonir** [dragonir/BLOG_ISSUE#27]
> 面对浏览器日益蓬勃的发展，web端技术也越来越多的被使用在移动开发中，为了提高用户体验， 作为前端工程师的我们要设计各式各样的交互效果，通过css3如何去控制动画的状态呢？下面我们 来看一看 animation-play-state的特性吧。

## animation-play-state是什么

属性定义一个动画是否运行或者暂停。可以通过查询它来确定动画是否正在运行。另外，它的值可 以被设置为暂停和恢复的动画的重放。

```css
{
  animation-play-state: paused | running;
  //paused 暂停 running 运行
}
```

## animation-play-state怎么用

```html
<div class="btn">stop</div>
<div class="animation"></div>
<style>
  .animation {
    animation: move 2s linear infinite alternate;
  }
  @keyframes move {
    0% { transform: translate(-100px, 0);}
    100% { transform: translate(100px, 0);}
  }
</style>
<script>
  document.querySelector('.btn').addEventListener('click', function() {
    let btn = document.querySelector('.btn');
    let elem = document.querySelector('.animation');
    let state = elem.style['animationPlayState'];
    if(state === 'paused') {
      elem.style['animationPlayState'] = 'running';
      btn.innerText = 'stop';
    } else {
      elem.style['animationPlayState'] = 'paused';
      btn.innerText = 'play';
    }
  });
</script>
```

## css鼠标触动实现动画控制

使用 hover 伪类，在鼠标悬停在按钮上面时，控制动画样式的暂停。代码如下：

```css
&:hover {
  animation-play-state: paused;
}
```

## css:checked伪类实现动画控制

通过input的checked伪类，我们就很容易实现单击表单按钮，实现关联操作动画的状态

```html
<input id="stop" type="radio" name="playAnimation" />
<input id="play" type="radio" name="playAnimation" />
<div class="box">
  <label for="stop"><div class="btn">stop</div></label>
  <label for="play"> <div class="btn">play</div></label>
</div>
<div class="animation"></div>
```

```css
.animation {
  animation: move 2s linear infinite alternate;
}
#stop:checked ~ .animation {
  animation-play-state: paused;
}
#play:checked ~ .animation {
  animation-play-state: running;
}
```

## 使用场景

* 状态切换动画。
* 手势触发动画。
