### ISSUE TITLE
animation-direction: alternate

### ISSUE THREAD

**Issue by dragonir** [dragonir/BLOG_ISSUE#31]
## 用法

```css
div
{
  animation-direction:alternate;
  -webkit-animation-direction:alternate; /* Safari 和 Chrome */
}
```

## 定义和用法

animation-direction 属性定义是否应该轮流反向播放动画。

如果 animation-direction 值是 "alternate"，则动画会在奇数次数（1、3、5 等等）正常播放，而在偶数次数（2、4、6 等等）向后播放。

注释：如果把动画设置为只播放一次，则该属性没有效果。

## 语法

```css
animation-dirextion: normal | alternate;
```
