### ISSUE TITLE
margin-before margin-start

### ISSUE THREAD

**Issue by dragonir** [dragonir/BLOG_ISSUE#32]
```css
-webkit-margin-before: 1em;
-webkit-margin-after: 1em;
```

分别定义p的上边距和下边距的数值是`1倍`字体高度

```css
-webkit-margin-start: 0px;
-webkit-margin-end: 0px;
```

上面二句则定义为左右边距都为`0px`

因此

```css
p {
  display: block;
  -webkit-margin-before: 1em;
  -webkit-margin-after: 1em;
  -webkit-margin-start: 0px;
  -webkit-margin-end: 0px;
}
```

相当于CSS2.0中的

```css
p {
  display: block;
  margin-top: 1em;
  margin-bottom: 1em;
  margin-right: 0px;
  margin-left: 0px;
}
```
