### ISSUE TITLE
使用系统默认字体

### ISSUE THREAD

**Issue by dragonir** [dragonir/BLOG_ISSUE#33]
```css
  html { font-family: system-ui; }
```

相比 `system-ui` 的兼容性问题，更好的方法就是使用 `font` 关键字，这是标准属性， 10 年前浏览器就支持了，可以放心使用。`CSS` 代码如下(三选一即可):

## 方法一

```css
html { font: menu }
body { font-size: 16px }
```

## 方法二

```css
html { font: small-caption }
body { font-size: 16px }
```

## 方法三

```css
html { font: status-bar }
body { font-size: 16px }
```
